#include "hal_data.h"
#include "wqs_sensor.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    // Initialize FSP common resources (clocks/pins abstraction, etc.).
    g_hal_init();

    // UART command + sensor data wrapper.
    wqs_cmd_t wqs_cmd = {0};
    WQS_Init(&wqs_cmd);

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif

#if 0
    // Keep compiler happy in case you enable secure build jump.
    while (1) { }
#endif

    // Main loop: periodically send "detect" and read back all parameters.
    // Spec建议连续测量间隔 5~10s，这里取 6s。
    while (1)
    {
        (void)WQS_CmdSend(&wqs_cmd, WQS_CMD_TYPE_DETECT);

        // Read + parse all values (TOC/COD/色度/浊度/温度/TDS/UV254/电导率/WQI).
        (void)WQS_InfoGet((volatile wqs_info_t*)&g_wqs_info);

        g_wqs_measure_count++;
        g_wqs_last_read_ok = g_wqs_info.wqs_crc_ok;

        R_BSP_SoftwareDelay(6000U, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

#if BSP_TZ_SECURE_BUILD
FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
