#include "hal_data.h"
#include <stdio.h>
#include "soil_moisture_adc.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

uint16_t adc_raw;
uint8_t  moisture_percent;

void hal_entry(void)
{
    soil_adc_init();

    while (1) 
    {
        adc_raw = soil_adc_read_raw();
        moisture_percent = soil_adc_raw_to_percent(adc_raw);

        //printf("ADC_RAW=%u, Moisture=%u%%\r\n", adc_raw, moisture_percent);   Use "Watch" to observe
        R_BSP_SoftwareDelay(500U, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
