#include "hal_data.h"
#include "dev_pump_driver.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

/* debug */
pump_set_t Pump_Set;

void hal_entry(void)
{
    /* TODO: add your own code here */
    Pump_Init(&Pump_Set);
    Pump_ModeSet(&Pump_Set, PUMP_ACTIVE);
    Pump_Start(&Pump_Set);

    while(1)
    {
        Pump_FlowrateSet(&Pump_Set, 500);
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
        Pump_FlowrateSet(&Pump_Set, 10000);
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
