#include "hal_data.h"

uint8_t g_data = 0x12;

void g_iic_b_master0_callback(i2c_master_callback_args_t *p_args)
{
    ;
}

void sci_i2c_master_callback(i2c_master_callback_args_t *p_args)
{
    ;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    R_SCI_I2C_Open(&g_i2c0_ctrl, &g_i2c0_cfg);
//    R_IIC_B_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg);
    while(1)
    {
        R_SCI_I2C_Write(&g_i2c0_ctrl, &g_data, sizeof(g_data), false);
//        R_IIC_B_MASTER_Write(&g_i2c_master0_ctrl, &g_data, sizeof(g_data), false);
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
