#include "hal_data.h"
#include "dev_ths_driver.h"

void sci_i2c_master_callback(i2c_master_callback_args_t *p_args)
{

}

uint8_t g_data = 0x2D;
ths_cmd_t g_ths_cmd;
ths_data_t g_ths_data;
float g_ths_temp, g_ths_rh;
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    R_SCI_I2C_Open(&g_i2c0_ctrl, &g_i2c0_cfg);
    THS_PeriodicModeStart(&g_ths_cmd, THS_REPEAT_TYPE_HIGH);
    while(1)
    {
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
        THS_PeriodicDataRead(&g_ths_cmd, &g_ths_data);
        //debug
        g_ths_temp = g_ths_data.ths_data_temp;
        g_ths_rh = g_ths_data.ths_data_rh;

    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
