#include "hal_data.h"
#include "dev_uwts_driver.h"

uwts_data_t g_uwts_data;
float g_temp_real = 0.0f;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
    UWTS_Init();
    while(1)
    {
        UWTS_ConversionStart(&g_uwts_data);
        /* 等待转换完成（最大750ms）*/
        R_BSP_SoftwareDelay(750, BSP_DELAY_UNITS_MILLISECONDS);
        UWTS_TemperatureRead(&g_uwts_data);

        //debug
        g_temp_real = g_uwts_data.uwts_data_temp_real;

        R_BSP_SoftwareDelay(2, BSP_DELAY_UNITS_SECONDS);
    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
