#include "hal_data.h"
#include "dev_water_quality_sen.h"

//uint8_t g_data[7] = {'A', 'B', 'C', 'D', 'E', 'F', '\n'};
wqs_cmd_t g_wqs_cmd;
wqs_info_t g_wqs_info;
float g_temp_get;
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    R_SCI_UART_Open(&g_uart_debug_ctrl, &g_uart_debug_cfg);
    WQS_Init(&g_wqs_cmd);
//    WQS_CmdSend(&g_wqs_cmd, WQS_CMD_TYPE_DETECT);
    while(1)
    {
//        R_SCI_UART_Write(&g_uart0_ctrl, g_data, sizeof(g_data));
        WQS_CmdSend(&g_wqs_cmd, WQS_CMD_TYPE_DETECT);
        R_BSP_SoftwareDelay(3, BSP_DELAY_UNITS_SECONDS);
        WQS_InfoGet(&g_wqs_info);
//        g_temp_get = g_wqs_info.wqs_info_temp;
        R_BSP_SoftwareDelay(3, BSP_DELAY_UNITS_SECONDS);
    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
