#include "hal_data.h"
#include "dev_soil_humid_sen_driver.h"

//void SHS_ScanCpltCallback(adc_callback_args_t *p_args)
//{
//    R_ADC_Read(&g_shs_adc_ctrl, ADC_CHANNEL_1, &g_data);
//}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
//    R_ADC_Open(&g_shs_adc_ctrl, &g_shs_adc_cfg);
//    R_ADC_ScanCfg(&g_shs_adc_ctrl, &g_shs_adc_channel_cfg);
//    R_ADC_ScanStart(&g_shs_adc_ctrl);
    SHS_Init();
    SHS_ScanStart();
    while(1)
    {

    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
