#include "hal_data.h"

uint16_t g_humidity = 0;
uint8_t g_t = 0;
volatile bool status = false;
double g_conv;

void ADC_Init(void)
{
    fsp_err_t err;
    err = R_ADC_Open(&g_adc0_ctrl, &g_adc0_cfg);
    err = R_ADC_ScanCfg(&g_adc0_ctrl, &g_adc0_channel_cfg);
    assert(FSP_SUCCESS == err);
}

void ADC0_ScanCpltCallback(adc_callback_args_t *p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);
    status = true;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
//    R_ADC_ScanStart(&g_adc0_ctrl);
    ADC_Init();
    R_SCI_UART_Open(&g_uart0_ctrl, &g_uart0_cfg);
    while(1)
    {
        R_ADC_ScanStart(&g_adc0_ctrl);
        while(!status);
        status = false;
        R_ADC_Read(&g_adc0_ctrl, ADC_CHANNEL_2, &g_humidity);
        R_SCI_UART_Write(&g_uart0_ctrl, &g_humidity, 1);
        g_t++;
        R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MILLISECONDS);
//      g_t++;
//        R_SCI_UART_Write(&g_uart0_ctrl, &g_t, 1);
//        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
