#include "hal_data.h"
#include "global.h"
#include "arm_control.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

// 机械臂控制对象
static arm_control_t g_arm_ctrl;

void hal_entry(void)
{
    /* 初始化机械臂控制 */
    // 打开串口（用于舵机通信）
    R_SCI_UART_Open(&g_serial_servo_uart_ctrl, &g_serial_servo_uart_cfg);
    
    // 初始化机械臂控制模块
    ArmControl_Init(&g_arm_ctrl);
    
    // 等待系统稳定
    R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);
    
    // 复位机械臂到初始位置
    ArmControl_Reset(&g_arm_ctrl, 2000); // 2秒内移动到初始位置
    R_BSP_SoftwareDelay(2500, BSP_DELAY_UNITS_MILLISECONDS);
    
    /* 示例1：通过逆运动学控制末端位置 */
    // 设置目标位置：x=20cm, y=5cm, z=10cm, 俯仰角=0度
    kin_status_t status = ArmControl_EndPositionSet(&g_arm_ctrl, 20.0f, 5.0f, 10.0f, 0.0f, 2000);
    if (status == KIN_STATUS_OK)
    {
        // 位置设置成功，等待运动完成
        R_BSP_SoftwareDelay(2500, BSP_DELAY_UNITS_MILLISECONDS);
    }
    
    /* 示例2：直接设置关节角度 */
    // 设置4个关节的角度：基座=30度，肩部=60度，肘部=45度，腕部=-30度
    float joint_angles[4] = {30.0f, 60.0f, 45.0f, -30.0f};
    ArmControl_AllJointsSet(&g_arm_ctrl, joint_angles, 2000);
    R_BSP_SoftwareDelay(2500, BSP_DELAY_UNITS_MILLISECONDS);
    
    /* 示例3：单独控制某个关节 */
    // 只改变基座旋转角度
    ArmControl_JointAngleSet(&g_arm_ctrl, 0, 45.0f, 1000);
    R_BSP_SoftwareDelay(1500, BSP_DELAY_UNITS_MILLISECONDS);
    
    /* 主循环 */
    while(1)
    {
        // 在这里可以添加：
        // 1. 接收外部控制命令（PC/蓝牙）
        // 2. 执行预设的运动轨迹
        // 3. 实时位置反馈和调整
        
        // 示例：循环运动
        // ArmControl_EndPositionSet(&g_arm_ctrl, 15.0f, 0.0f, 5.0f, 0.0f, 2000);
        // R_BSP_SoftwareDelay(2500, BSP_DELAY_UNITS_MILLISECONDS);
        // ArmControl_EndPositionSet(&g_arm_ctrl, 15.0f, 0.0f, 15.0f, 0.0f, 2000);
        // R_BSP_SoftwareDelay(2500, BSP_DELAY_UNITS_MILLISECONDS);
        
        R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
