#include "hal_data.h"
#include "global.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

//uint8_t g_data[4] = {0x55, 0x55, 0x3B, 0x90};

void hal_entry(void)
{
    /* TODO: add your own code here */
//	R_SCI_UART_Open(&g_serial_servo_uart_ctrl, &g_serial_servo_uart_cfg);
	while(1)
	{
//		R_SCI_UART_Write(&g_serial_servo_uart_ctrl, g_data, sizeof(g_data));
//		R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
	}

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
