#include "hal_data.h"
#include "arm_control.h"
#include "serial_servo.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

// 机械臂控制对象（用于调试 ArmControl_EndPositionSet）
arm_control_t g_arm_ctrl;
servo_ctrl_t g_servo_ctrl;
kin_status_t g_kin_status;

void hal_entry(void)
{
	R_SCI_UART_Open(&g_serial_servo_uart_ctrl, &g_serial_servo_uart_cfg);
    ArmControl_Init(&g_arm_ctrl);
//	Servo_Init(&g_servo_ctrl);
    R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
    while(1)
    {
        ArmControl_EndPositionSet(&g_arm_ctrl, 18.0f, 0.0f, 6.0f, 0.0f, 1000);
//		Servo_PositionSet(&g_servo_ctrl, 1, 405, 300);
		R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
//		g_kin_status = KIN_STATUS_OK;
//		R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
