#include "hal_data.h"
#include "dev_press_sen_driver.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

ps_data_t g_ps_data[PS_NUM];
uint16_t HE_data;

void hal_entry(void)
{
    /* TODO: add your own code here */

    PS_Init();
    PS_ScanStart();
    while(1)
    {
        PS_DataRawGet(PS_MEDIUM, g_ps_data);
        HE_data = g_ps_data[PS_MEDIUM].ps_data_raw;     //debug
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
